/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: d4032ab3159e454729d32b12ad1e9e6c)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
    durableNamespaces: "DevAgent";
  }
  interface Env {
    SCREENSHOTS: R2Bucket;
    DB: D1Database;
    EMAIL: SendEmail;
    BROWSER: Fetcher;
    ASSETS: Fetcher;
    OPENAI_API_KEY: string;
    ADMIN_EMAIL_TO: string;
    ADMIN_EMAIL_FROM: string;
    ALLOW_LIST: string;
    DevAgent: DurableObjectNamespace<import("./src/worker").DevAgent>;
    ONBOARDING_WORKFLOW: Workflow<
      Parameters<import("./src/worker").OnboardingWorkflow["run"]>[0]["payload"]
    >;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      "OPENAI_API_KEY" | "ADMIN_EMAIL_TO" | "ADMIN_EMAIL_FROM" | "ALLOW_LIST"
    >
  > {}
}
declare module "*.sql" {
  const value: string;
  export default value;
}
