/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 8516b15d0d865a9c9277d3c80d1a4f1d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "DevAgent";
	}
	interface Env {
		SCREENSHOTS: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		BROWSER: Fetcher;
		ASSETS: Fetcher;
		OPENAI_API_KEY: string;
		DevAgent: DurableObjectNamespace<import("./src/worker").DevAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}